# Generated by Django 6.0.4 on 2026-04-19 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_anotacao_data_atualizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='ativo',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ano_avaliado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='processo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='proxima_progressao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_progressao', 'Em Progressao')], default='ativo', max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(choices=[('docente', 'Docente'), ('tecnico', 'Tecnico')], default='docente', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anotacao',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotacoes', to='agendamento.funcionario'),
        ),
        migrations.AlterField(
            model_name='anotacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
