# Generated by Django 6.0.4 on 2026-04-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('processo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_avaliado', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('proxima_progressao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_progressao', 'Em Progressao')], default='ativo', max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('docente', 'Docente'), ('tecnico', 'Tecnico')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('data_contratacao', models.DateField(blank=True, null=True, verbose_name='Data de Contratação')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
