# Generated by Django 6.0.4 on 2026-04-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_contratacao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='status',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nivel',
            field=models.CharField(default=1, max_length=2, verbose_name='Nível'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='progrediu',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Progrediu'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(choices=[('DO', 'Docente'), ('TE', 'Técnico')], max_length=2, verbose_name='Tipo'),
        ),
    ]
