# Generated by Django 6.0.4 on 2026-04-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_funcionario_data_contratacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='ano_avaliado',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, default='sememail@teste.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(default='00000', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='processo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='proxima_progressao',
            field=models.DateField(blank=True, default='2024-01-01'),
            preserve_default=False,
        ),
    ]
