# Generated by Django 6.0.4 on 2026-04-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='progrediu',
        ),
    ]
