# Generated by Django 6.0.4 on 2026-05-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_funcionario_progrediu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='ativo',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendente'), ('EA', 'Em andamento'), ('FI', 'Finalizado')], default=1, max_length=2, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
