# Generated by Django 6.0.4 on 2026-05-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_remove_funcionario_ativo_funcionario_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='suap',
            field=models.URLField(blank=True, null=True, verbose_name='Suap'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('EA', 'Em andamento'), ('FI', 'Finalizado'), ('PE', 'Pendente')], default='EA', max_length=2, verbose_name='Status'),
        ),
    ]
