# Generated by Django 5.2.11 on 2026-04-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
    ]
