# Generated by Django 6.0.4 on 2026-04-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anotacoes', '0003_remove_funcionario_ativo_funcionario_ano_avaliado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotacao',
            name='funcionario',
        ),
    ]
