# Generated by Django 6.0.4 on 2026-04-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anotacoes', '0004_remove_anotacao_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
