# Generated by Django 6.0.4 on 2026-04-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotacoes', '0005_delete_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotacao',
            name='data_atualizacao',
        ),
        migrations.AlterField(
            model_name='anotacao',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
