# Generated by Django 6.0.4 on 2026-05-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotacoes', '0006_remove_anotacao_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacao',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
    ]
