# Generated by Django 6.0.4 on 2026-05-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=50)),
                ('data_inicio', models.DateField(blank=True)),
                ('data_encerramento', models.DateField(blank=True)),
                ('avaliacao_1', models.CharField(choices=[('EA', 'Em andamento'), ('FI', 'Finalizado'), ('PE', 'Pendente')], default='EA', max_length=2, verbose_name='Status')),
                ('avaliacao_2', models.CharField(choices=[('EA', 'Em andamento'), ('FI', 'Finalizado'), ('PE', 'Pendente')], default='EA', max_length=2, verbose_name='Status')),
                ('avaliacao_3', models.CharField(choices=[('EA', 'Em andamento'), ('FI', 'Finalizado'), ('PE', 'Pendente')], default='EA', max_length=2, verbose_name='Status')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('suap', models.URLField(blank=True, null=True, verbose_name='Suap')),
            ],
            options={
                'verbose_name': 'Probatório',
                'verbose_name_plural': 'Probatórios',
                'ordering': ['nome'],
            },
        ),
    ]
