# Generated by Django 6.0.4 on 2026-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prazos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probatorio',
            options={'ordering': ['nome'], 'verbose_name': 'Estágio Probatório', 'verbose_name_plural': 'Estágios Probatórios'},
        ),
        migrations.AlterField(
            model_name='probatorio',
            name='data_encerramento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
