# Generated by Django 6.0.4 on 2026-05-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prazos', '0002_alter_probatorio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('matricula', models.CharField(max_length=50)),
                ('vaga', models.CharField(max_length=100, verbose_name='Contrato')),
                ('data_inicio', models.DateField(blank=True)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('suap', models.URLField(blank=True, null=True, verbose_name='Processo SUAP')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('SU', 'Substituto'), ('EG', 'Estagiário')], max_length=2, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['nome'],
            },
        ),
    ]
