# Generated by Django 6.0.4 on 2026-05-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prazos', '0003_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('EA', 'Em andamento'), ('FI', 'Finalizado'), ('PE', 'Pendente')], default='EA', max_length=2, verbose_name='Status'),
        ),
    ]
